### ISSUE TITLE
.icon returning bad URI

### ISSUE THREAD

**Issue by chrisbutlerccc** [jnunemaker/google-weather#6]
When I try to use .icon for a weather object it gives me a URI like this:

http://google.com/ig/images/weather/cloudy.gif

Which is incorrect. There should be no 'ig' in the URI for it to work...

http://google.com/images/weather/cloudy.gif

Maybe Google updated something?

**Comment by marktabler** [comment]
This is going to sound crazy - and perhaps it is - but the correct URI is actually http://www.google.com/ig/images/weather/cloudy.gif .  For some reason, if you add the /ig element to the URI you also have to specify the www subdomain.  

The API itself returns "/ig/images/weather/cloudy.gif", with no domain specified at all.  It seems that the correct case here is to continue using the relative path that the API provides and specify http://www.google.com as the domain to look for.

**Comment by jnunemaker** [comment]
Weird. Closing since it doesn't seem to be the gem (unless I'm misunderstanding).
